

export const ActionTypes = {
	SET_FRONTEND_PROJECTS: 'SET_FRONTEND_PROJECTS',
	SET_BACKEND_PROJECTS: 'SET_BACKEND_PROJECTS',
	SET_VANILLAJS_PROJECTS: 'SET_VANILLAJS_PROJECTS',
	SET_WEB-DESIGN_PROJECTS: 'SET_WEB-DESIGN_PROJECTS'
};

